CREATE TABLE `account` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`user_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`id_token` text,
	`access_token_expires_at` integer,
	`refresh_token_expires_at` integer,
	`scope` text,
	`password` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `account_userId_idx` ON `account` (`user_id`);--> statement-breakpoint
CREATE TABLE `session` (
	`id` text PRIMARY KEY NOT NULL,
	`expires_at` integer NOT NULL,
	`token` text NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`user_id` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);--> statement-breakpoint
CREATE INDEX `session_userId_idx` ON `session` (`user_id`);--> statement-breakpoint
CREATE TABLE `user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);--> statement-breakpoint
CREATE TABLE `verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);--> statement-breakpoint
CREATE TABLE `ingredient` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer,
	`user_id` text,
	`favourite_at` integer,
	`deleted_at` integer,
	`hidden_at` integer,
	`is_aus_food` integer,
	`is_all_stores` integer DEFAULT true,
	`serve_size` text,
	`serve_unit` text,
	`public_food_key` text,
	`classification` text,
	`food_name` text,
	`name` text,
	`calories_w_fibre` text,
	`calories_wo_fibre` text,
	`protein` text,
	`fat_total` text,
	`total_dietary_fibre` text,
	`total_sugars` text,
	`starch` text,
	`resistant_starch` text,
	`available_carbohydrate_without_sugar_alcohols` text,
	`available_carbohydrate_with_sugar_alcohols` text,
	`is_user_created` integer DEFAULT false,
	`is_supplement` integer DEFAULT false,
	`is_private` integer DEFAULT false,
	`viewable_by` text,
	`intervale` text,
	`notes` text,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `ingredient_addition_one` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer,
	`ingredient_id` integer,
	`energy_with_dietary_fibre` text,
	`energy_without_dietary_fibre` text,
	`added_sugars` text,
	`free_sugars` text,
	`moisture` text,
	`nitrogen` text,
	`alcohol` text,
	`fructose` text,
	`glucose` text,
	`sucrose` text,
	`maltose` text,
	`lactose` text,
	`galactose` text,
	`maltotrios` text,
	`ash` text,
	`dextrin` text,
	`glycerol` text,
	`glycogen` text,
	`inulin` text,
	`erythritol` text,
	`maltitol` text,
	`mannitol` text,
	`xylitol` text,
	`maltodextrin` text,
	`oligosaccharides` text,
	`polydextrose` text,
	`raffinose` text,
	`stachyose` text,
	`sorbitol` text,
	FOREIGN KEY (`ingredient_id`) REFERENCES `ingredient`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `ingredient_addition_three` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer,
	`ingredient_id` integer,
	`total_saturated_fatty_acids` text,
	`total_monounsaturated_fatty_acids` text,
	`total_polyunsaturated_fatty_acids` text,
	`total_long_chain_omega_3_fatty_acids` text,
	`total_trans_fatty_acids` text,
	`caffeine` text,
	`cholesterol` text,
	`alanine` text,
	`arginine` text,
	`aspartic_acid` text,
	`cystine_plus_cysteine` text,
	`glutamic_acid` text,
	`glycine` text,
	`histidine` text,
	`isoleucine` text,
	`leucine` text,
	`lysine` text,
	`methionine` text,
	`phenylalanine` text,
	`proline` text,
	`serine` text,
	`threonine` text,
	`tyrosine` text,
	`tryptophan` text,
	`valine` text,
	`c4` text,
	`c6` text,
	`c8` text,
	`c10` text,
	`c11` text,
	`c12` text,
	`c13` text,
	`c14` text,
	`c15` text,
	`c16` text,
	`c17` text,
	`c18` text,
	`c19` text,
	`c20` text,
	`c21` text,
	`c22` text,
	`c23` text,
	`c24` text,
	`total_saturated_fatty_acids_equated` text,
	`c10_1` text,
	`c12_1` text,
	`c14_1` text,
	`c15_1` text,
	`c16_1` text,
	`c17_1` text,
	`c18_1` text,
	`c18_1w5` text,
	`c18_1w6` text,
	`c18_1w7` text,
	`c18_1w9` text,
	`c20_1` text,
	`c20_1w9` text,
	`c20_1w13` text,
	`c20_1w11` text,
	`c22_1` text,
	`c22_1w9` text,
	`c22_1w11` text,
	`c24_1` text,
	`c24_1w9` text,
	`c24_1w11` text,
	`c24_1w13` text,
	`total_monounsaturated_fatty_acids_equated` text,
	`c12_2` text,
	`c16_2w4` text,
	`c16_3` text,
	`c18_2w6` text,
	`c18_3w3` text,
	`c18_3w4` text,
	`c18_3w6` text,
	`c18_4w1` text,
	`c18_4w3` text,
	`c20_2` text,
	`c20_2w6` text,
	`c20_3` text,
	`c20_3w3` text,
	`c20_3w6` text,
	`c20_4` text,
	`c20_4w3` text,
	`c20_4w6` text,
	`c20_5w3` text,
	`c21_5w3` text,
	`c22_2` text,
	`c22_2w6` text,
	`c22_4w6` text,
	`c22_5w3` text,
	`c22_5w6` text,
	`c22_6w3` text,
	`total_polyunsaturated_fatty_acids_equated` text,
	FOREIGN KEY (`ingredient_id`) REFERENCES `ingredient`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `ingredient_addition_two` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer,
	`ingredient_id` integer,
	`acetic_acid` text,
	`citric_acid` text,
	`fumaric_acid` text,
	`lactic_acid` text,
	`malic_acid` text,
	`oxalic_acid` text,
	`propionic_acid` text,
	`quinic_acid` text,
	`shikimic_acid` text,
	`succinic_acid` text,
	`tartaric_acid` text,
	`aluminium` text,
	`antimony` text,
	`arsenic` text,
	`cadmium` text,
	`calcium` text,
	`chromium` text,
	`chloride` text,
	`cobalt` text,
	`copper` text,
	`fluoride` text,
	`iodine` text,
	`iron` text,
	`lead` text,
	`magnesium` text,
	`manganese` text,
	`mercury` text,
	`molybdenum` text,
	`nickel` text,
	`phosphorus` text,
	`potassium` text,
	`selenium` text,
	`sodium` text,
	`sulphur` text,
	`tin` text,
	`zinc` text,
	`retinol` text,
	`alpha_carotene` text,
	`beta_carotene` text,
	`cryptoxanthin` text,
	`beta_carotene_equivalents` text,
	`vitamin_a_retinol_equivalents` text,
	`lutein` text,
	`lycopene` text,
	`xanthophyl` text,
	`thiamin` text,
	`riboflavin` text,
	`niacin` text,
	`niacin_derived_from_tryptophan` text,
	`niacin_derived_equivalents` text,
	`pantothenic_acid` text,
	`pyridoxine` text,
	`biotin` text,
	`cobalamin` text,
	`folate_natural` text,
	`folic_acid` text,
	`total_folates` text,
	`dietary_folate_equivalents` text,
	`vitamin_c` text,
	`cholecalciferol` text,
	`ergocalciferol` text,
	`hydroxy_cholecalciferol` text,
	`hydroxy_ergocalciferol` text,
	`vitamin_d_equivalents` text,
	`alpha_tocopherol` text,
	`alpha_tocotrienol` text,
	`beta_tocopherol` text,
	`beta_tocotrienol` text,
	`delta_tocopherol` text,
	`delta_tocotrienol` text,
	`gamma_tocopherol` text,
	`gamma_tocotrienol` text,
	`vitamin_e` text,
	FOREIGN KEY (`ingredient_id`) REFERENCES `ingredient`(`id`) ON UPDATE no action ON DELETE cascade
);
